project_name: telegen-sonic

before:
  hooks:
    - go mod tidy

builds:
  - id: telegen-sonic
    main: ./cmd/telegen-sonic
    env:
      - CGO_ENABLED=0
    goos: [ linux, darwin, windows ]
    goarch: [ amd64, arm64 ]
    flags: [ -trimpath ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - formats: [ tar.gz ]
    # Use zip for Windows for better UX
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# (Optional) Publish the same image via GoReleaser as well
dockers:
  - id: telegen-sonic-img
    image_templates:
      - ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Version }}
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: [ amd64, arm64 ]
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
    extra_files:
      - LICENSE

release:
  draft: false
  replace_existing_draft: true
  prerelease: auto
