name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build BPF
        run: |
          sudo apt-get update
          sudo apt-get install -y clang llvm make
          make -C bpf
      - name: Go Build
        run: make build
      - name: Go Test
        run: go test ./...
      - name: Docker build
        run: docker build -t telegen-sonic:ci -f deploy/Dockerfile .
