name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install eBPF toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang llvm libbpf-dev libelf-dev bpftool make pkg-config

      - name: Build eBPF objects
        working-directory: bpf
        run: make

      - name: Build (all modules)
        run: go build ./...

      - name: Run tests
        run: go test -race -count=1 ./...

      - name: Verify static binary builds
        run: |
          CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" ./...
