name: e2e

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (format: release/mark-vMAJOR-MINOR-PATCH)'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  GO_VERSION: '1.23.x'
  GOFLAGS: -mod=readonly
  RELEASE_TAG: ${{ inputs.tag }}

concurrency:
  group: e2e-release-${{ github.run_id }}
  cancel-in-progress: false

jobs:
  create-tag:
    name: Create tag (manual, owner/admin only)
    runs-on: ubuntu-latest
    steps:
      - name: "Guard: only repository admins/owners may run releases"
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner.toLowerCase();
            const repo  = context.repo.repo;
            const actor = context.actor.toLowerCase();

            if (owner === actor) {
              core.info(`Actor ${actor} is the repo owner (${owner}); allowed.`);
              return;
            }
            const { data } = await github.rest.repos.getCollaboratorPermissionLevel({
              owner, repo, username: context.actor
            });
            if (data.permission !== 'admin') {
              core.setFailed('Only repository admins/owners may run release workflow.');
            }

      - name: "Validate tag format"
        run: |
          TAG="${{ env.RELEASE_TAG }}"
          if [[ ! "$TAG" =~ ^release/mark-v[0-9]+-[0-9]+-[0-9]+$ ]]; then
            echo "Tag must match release/mark-vMAJOR-MINOR-PATCH (e.g. release/mark-v1-2-3)"
            exit 1
          fi

      - name: "Create git tag (lightweight) if missing"
        id: createref
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.RELEASE_TAG;
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            try {
              await github.rest.git.getRef({ owner, repo, ref: `tags/${tag}` });
              core.info(`Tag ${tag} already exists.`);
              core.setOutput('created', 'false');
            } catch (e) {
              if (e.status !== 404) throw e;
              const sha = context.sha;
              await github.rest.git.createRef({ owner, repo, ref: `refs/tags/${tag}`, sha });
              core.info(`Created refs/tags/${tag} -> ${sha}`);
              core.setOutput('created', 'true');
            }

      - name: "Ensure draft GitHub Release exists for the tag"
        uses: actions/github-script@v7
        with:
          script: |
            const tag   = process.env.RELEASE_TAG;
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            try {
              const rel = await github.rest.repos.getReleaseByTag({ owner, repo, tag });
              core.info(`Release for ${tag} already exists (id=${rel.data.id}).`);
              return;
            } catch (e) {
              if (e.status !== 404) throw e;
            }

            const res = await github.rest.repos.createRelease({
              owner, repo,
              tag_name: tag,
              target_commitish: context.sha,
              name: tag,
              body: `Draft release for **${tag}** (created by workflow). Artifacts will be attached by CI.`,
              draft: true,
              prerelease: false,
              generate_release_notes: true
            });
            core.info(`Created draft release id=${res.data.id} for tag ${tag}.`)

  govulncheck:
    name: Security gate (govulncheck FIRST)
    runs-on: ubuntu-latest
    needs: [create-tag]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Verify modules resolve (RO mode)
        run: go list ./... >/dev/null

      - name: Run govulncheck (JSON)
        id: vuln
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.23'
          go-package: ./...
          output-format: json
          output-file: govuln.json
          check-latest: true
          cache: true

      # Compute count cleanly; DO NOT echo anything to $GITHUB_OUTPUT except KEY=VAL
      - name: Compute findings count (no fail)
        id: count
        run: |
          sudo apt-get update -y && sudo apt-get install -y jq
          COUNT="$(jq -r '.vulns | length' govuln.json)"
          printf "count=%s\n" "$COUNT" >> "$GITHUB_OUTPUT"
          printf "GOVULN_COUNT=%s\n" "$COUNT" >> "$GITHUB_ENV"

      - name: Fail on findings (hard gate)
        run: |
          if [ "${{ steps.count.outputs.count }}" -gt 0 ]; then
            echo "❌ Vulnerabilities detected by govulncheck: ${{ steps.count.outputs.count }}"
            exit 1
          fi
          echo "✅ No vulnerabilities found"

      # Always prepare the report & PR for visibility, even if the gate failed
      - name: Prepare report & README update
        if: ${{ always() }}
        run: |
          set -euxo pipefail
          sudo apt-get install -y jq
          TAG="${{ env.RELEASE_TAG }}"
          SAFE_TAG="${TAG//\//-}"
          mkdir -p reports/govulncheck
          jq '.' govuln.json > "reports/govulncheck/${SAFE_TAG}.json"

          COUNT="${GOVULN_COUNT:-0}"
          DATE="$(date -u +'%Y-%m-%d %H:%M:%SZ')"
          LINK="reports/govulncheck/${SAFE_TAG}.json"

          cat > .govul-section.md <<EOF
          <!-- GOVULNCHECK-START -->
          ### govulncheck

          | Field | Value |
          |------:|:------|
          | Tag | **${TAG}** |
          | Scan Time (UTC) | ${DATE} |
          | Findings | **${COUNT}** |
          | Full Report | [${LINK}](${LINK}) |

          _This section is auto-updated by the e2e release workflow._
          <!-- GOVULNCHECK-END -->
          EOF

          if grep -q '<!-- GOVULNCHECK-START -->' README.md; then
            START='<!-- GOVULNCHECK-START -->'
            END='<!-- GOVULNCHECK-END -->'
            awk -v s="$START" -v e="$END" '
              $0 ~ s {print; system("cat .govul-section.md"); skip=1; next}
              $0 ~ e {print; skip=0}
              skip==0 {print}
            ' README.md > README.md.new
            mv README.md.new README.md
          else
            printf "\n%s\n" >> README.md
            cat .govul-section.md >> README.md
          fi

      - name: Create PR with report & README
        if: ${{ always() }}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(govulncheck): add report for ${{ env.RELEASE_TAG }} and update README"
          branch: "chore/govulncheck-${{ env.RELEASE_TAG && env.RELEASE_TAG != '' && env.RELEASE_TAG || github.run_id }}-${{ github.run_id }}"
          title: "govulncheck: report for ${{ env.RELEASE_TAG }}"
          body: |
            This PR adds the **govulncheck** report for `${{ env.RELEASE_TAG }}` and updates the README summary section.
            Findings: `${{ env.GOVULN_COUNT || '0' }}`
          labels: |
            security
            automated-pr
          signoff: false
          delete-branch: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-test:
    name: Build & Test (runs only if govulncheck passed)
    runs-on: ubuntu-latest
    needs: [govulncheck]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install eBPF toolchain (clang/llvm/libbpf + bpftool)
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y clang llvm make gcc libelf-dev libbpf-dev pkg-config
          KREL="$(uname -r)"
          sudo apt-get install -y linux-tools-common linux-tools-generic linux-cloud-tools-generic || true
          sudo apt-get install -y "linux-tools-${KREL}" || true
          BPFOOL=""
          for p in /usr/sbin/bpftool /usr/bin/bpftool "/usr/lib/linux-tools-${KREL}/bpftool" /usr/lib/linux-tools-*/bpftool; do
            if [ -x "$p" ]; then BPFOOL="$p"; break; fi
          done
          if [ -z "$BPFOOL" ]; then
            echo "bpftool not found via apt; building from source..."
            sudo apt-get install -y git build-essential flex bison libcap-dev libzstd-dev
            git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git /tmp/bpf-next
            make -C /tmp/bpf-next/tools/bpf/bpftool
            BPFOOL=/tmp/bpf-next/tools/bpf/bpftool/bpftool
          fi
          echo "BPFOOL=$BPFOOL" >> "$GITHUB_ENV"
          "$BPFOOL" version

      - name: Prebuild eBPF objects
        if: ${{ hashFiles('bpf/Makefile') != '' }}
        working-directory: bpf
        env:
          BPFOOL: ${{ env.BPFOOL }}
        run: make

      - name: Sync modules
        run: |
          go env -w GOPROXY=https://proxy.golang.org,direct
          go mod tidy
          go mod download all

      - name: Build
        run: go build ./...

      - name: Test (race)
        run: go test -race -count=1 ./...

      - name: Verify static builds (sanity)
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" ./...

  docker:
    name: Build & Push Docker (tag == release tag)
    runs-on: ubuntu-latest
    needs: [build-test]
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4

      - name: Compute SAFE_TAG (slash -> dash)
        run: |
          echo "SAFE_TAG=${RELEASE_TAG//\//-}" >> "$GITHUB_ENV"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.SAFE_TAG }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.RELEASE_TAG }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  goreleaser:
    name: GoReleaser (binaries, exact tag)
    runs-on: ubuntu-latest
    needs: [build-test]
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Ensure bpftool & prebuild BPF
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y clang llvm make gcc libelf-dev libbpf-dev pkg-config
          KREL="$(uname -r)"
          sudo apt-get install -y "linux-tools-${KREL}" linux-tools-common || true
          BPFOOL="$(command -v bpftool || true)"
          if [ -z "$BPFOOL" ] && [ -x "/usr/lib/linux-tools-${KREL}/bpftool" ]; then BPFOOL="/usr/lib/linux-tools-${KREL}/bpftool"; fi
          if [ -z "$BPFOOL" ]; then echo "bpftool not found"; exit 1; fi
          echo "BPFOOL=$BPFOOL" >> "$GITHUB_ENV"
          (cd bpf && BPFOOL="$BPFOOL" make)

      - name: Sync modules
        run: |
          go env -w GOPROXY=https://proxy.golang.org,direct
          go mod tidy
          go mod download all

      - name: GoReleaser (tag from input)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          distribution: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.RELEASE_TAG }}