name: govulncheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scan:
    name: Run govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          # Scans all packages in the module
          go-version-input: '1.22'
          vulncheck-flags: ./...
