name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install eBPF toolchain (if release needs prebuilt BPF or Docker)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang llvm libbpf-dev libelf-dev bpftool make pkg-config

      - name: Prebuild eBPF objects (optional, safe if present)
        if: ${{ hashFiles('bpf/Makefile') != '' }}
        working-directory: bpf
        run: make

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          distribution: goreleaser

      - name: Release with GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --clean
